INSERT INTO games (title, description, genre, url, image_url, cover_url, icon_url)
VALUES ('Final Fantasy XIV Online',
        'Explore Eorzea in this acclaimed MMORPG. Known for its deep story and flexible class system.',
        'MMORPG', 'https://na.finalfantasyxiv.com/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/39210/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/39210/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/39210/logo.png'),
       ('Guild Wars 2',
        'A living, dynamic world where your actions have real consequences. No monthly subscription.',
        'MMORPG', 'https://www.guildwars2.com/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1284210/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1284210/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1284210/logo.png'),
       ('Hollow Knight',
        'Descend into the depths of Hallownest. A beautiful and challenging metroidvania.',
        'Metroidvania', 'https://www.hollowknight.com/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/logo.png'),
       ('Stardew Valley',
        'You inherited your grandfather''s old farm in Stardew Valley. Armed with second-hand tools and a few coins, you set out to begin your new life.',
        'Simulation', 'https://www.stardewvalley.net/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/logo.png'),
       ('The Elder Scrolls Online',
        'A limitless adventure in the Elder Scrolls universe. Play solo or with friends.',
        'MMORPG', 'https://www.elderscrollsonline.com/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/306130/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/306130/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/306130/logo.png'),
       ('Red Dead Redemption 2',
        'Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents on their trail, the gang must rob and fight to survive in the heart of America.',
        'Action Adventure', 'https://www.rockstargames.com/reddeadredemption2/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/logo.png'),
       ('Baldur ''s Gate 3',
        'Gather your party and return to the Forgotten Realms in a story of friendship, betrayal, sacrifice, and survival, with the lure of absolute power.',
        'RPG', 'https://baldursgate3.game/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/logo.png'),
       ('Grand Theft Auto V',
        'A street hustler, a retired bank robber, and a terrifying psychopath become entangled with some of the most frightening elements of the criminal underworld.',
        'Open World', 'https://www.rockstargames.com/gta-v',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/logo.png'),
       ('Hades',
        'Challenge the god of the dead as you battle to escape the Underworld in this roguelike dungeon crawler from the creators of Bastion and Transistor.',
        'Roguelike', 'https://www.supergiantgames.com/games/hades/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/library_600x900.jpg',
        'https://shared.fastly.steamstatic.com/community_assets/images/items/1145360/39820b1c38283d7f560e8cd41fee9d54896d7586.jpg'),
       ('Terraria',
        'Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. The world is your canvas and the ground your paint.',
        'Sandbox', 'https://terraria.org/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/105600/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/105600/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/105600/logo.png'),
       ('Cuphead',
        'Cuphead is a classic action game focused on boss battles. Inspired by 1930s animation, its visuals and audio were created using the same techniques of the era.',
        'Platformer', 'https://cupheadgame.com/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/268910/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/268910/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/268910/logo.png'),
       ('Cyberpunk 2077',
        'Enter Night City, a vast open world where your choices shape the story. Explore, hack, fight, and survive in this futuristic RPG.',
        'RPG', 'https://www.cyberpunk.net/',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/logo.png'),
       ('The Witcher 3: Wild Hunt',
        'Play as Geralt of Rivia, a monster hunter searching for his adopted daughter. Explore a rich open world full of choices, danger, and magic.',
        'RPG', 'https://thewitcher.com/en/witcher3',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_hero.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_600x900.jpg',
        'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/logo.png');

INSERT INTO launcher_deploys (system, version, description, url)
VALUES ('Windows', '1.0.0', 'basic game library support, simple UI, initial release, limited features',
        'https://example.com/launcher/1.0.0/download'),
       ('macOS', '1.0.0', 'basic game library support, simple UI, initial release, limited features',
        'https://example.com/launcher/1.0.0/mac/download'),
       ('Linux', '1.0.0', 'basic game library support, simple UI, initial release, limited features',
        'https://example.com/launcher/1.0.0/linux/download'),

       ('Windows', '1.1.0',
        'user profile management, improved UI responsiveness, minor bug fixes, performance improvements',
        'https://example.com/launcher/1.1.0/download'),
       ('macOS', '1.1.0',
        'user profile management, improved UI responsiveness, minor bug fixes, performance improvements',
        'https://example.com/launcher/1.1.0/mac/download'),
       ('Linux', '1.1.0',
        'user profile management, improved UI responsiveness, minor bug fixes, performance improvements',
        'https://example.com/launcher/1.1.0/linux/download'),

       ('Windows', '1.2.0', 'automatic updates, Windows bug fixes, performance improvements, UI tweaks',
        'https://example.com/launcher/1.2.0/download'),
       ('macOS', '1.2.0', 'automatic updates, macOS fixes, performance improvements, UI tweaks',
        'https://example.com/launcher/1.2.0/mac/download'),
       ('Linux', '1.2.0', 'automatic updates, Linux fixes, performance improvements, UI tweaks',
        'https://example.com/launcher/1.2.0/linux/download'),

       ('Windows', '2.0.0',
        'redesigned interface, cloud saves integration, improved download manager, stability improvements',
        'https://example.com/launcher/2.0.0/download'),
       ('macOS', '2.0.0',
        'redesigned interface, cloud saves integration, improved download manager, stability improvements',
        'https://example.com/launcher/2.0.0/mac/download'),
       ('Linux', '2.0.0',
        'redesigned interface, cloud saves integration, improved download manager, stability improvements',
        'https://example.com/launcher/2.0.0/linux/download'),

       ('Windows', '2.1.0', 'friends list, chat system, notifications support, UI enhancements',
        'https://example.com/launcher/2.1.0/download'),
       ('macOS', '2.1.0', 'friends list, chat system, notifications support, UI enhancements',
        'https://example.com/launcher/2.1.0/mac/download'),
       ('Linux', '2.1.0', 'friends list, chat system, notifications support, UI enhancements',
        'https://example.com/launcher/2.1.0/linux/download'),

       ('Windows', '3.0.0',
        'integrated mod support, custom themes, next-generation launcher features, improved performance',
        'https://example.com/launcher/3.0.0/download'),
       ('macOS', '3.0.0',
        'integrated mod support, custom themes, next-generation launcher features, improved performance',
        'https://example.com/launcher/3.0.0/mac/download'),
       ('Linux', '3.0.0',
        'integrated mod support, custom themes, next-generation launcher features, improved performance',
        'https://example.com/launcher/3.0.0/linux/download');
